"""Single-file PyTorch reproduction of WSRL.

WSRL: Efficient Online Reinforcement Learning Fine-Tuning Need Not Retain
Offline Data (ICLR 2025).

This file follows the paper and the author-released JAX/Flax repository while
keeping the same single-file PyTorch style used by the surrounding baselines.
It implements the full state-based experimental pipeline:

1. Initialize the actor and critic from offline RL pre-training. A compatible
   PyTorch checkpoint can be loaded directly, or the file can perform the main
   paper pre-training choice itself: Cal-QL for AntMaze/Adroit/Kitchen and CQL
   for MuJoCo locomotion.
2. Discard the offline dataset and initialize an empty online replay buffer.
3. Collect ``warmup_steps`` transitions with a frozen copy of the pre-trained
   policy and perform no gradient updates.
4. Continue interaction with the trainable policy and optimize standard SAC
   using online data only. Each environment step samples one super-batch,
   performs ``utd_ratio`` critic/target updates on disjoint mini-batches, then
   performs one actor and one temperature update on the entire super-batch.

Released/main-paper WSRL details represented here:

* 5,000 online warm-up steps with the frozen pre-trained policy.
* No offline transition retention during the WSRL fine-tuning phase.
* 10 Q-functions and LayerNorm after every hidden affine layer.
* UTD=4 with mini-batch size 256. The sampled super-batch therefore contains
  1,024 transitions; it is split into four critic mini-batches, while the actor
  and entropy temperature are updated once on all 1,024 transitions.
* Actor LR 1e-4, critic LR 3e-4, temperature LR 1e-4.
* Target entropy ``-action_dim``, discount 0.99, and Polyak coefficient 0.005.
* Entropy is used in the actor objective but not in the Bellman backup.
* AntMaze uses a state-independent policy standard deviation and max-Q target
  backup over 10 policy actions. WSRL uses a 10-Q ensemble and randomly
  subsamples two target critics (with replacement) before taking their minimum
  in every supported domain, including AntMaze.
* Offline actor/critic/temperature optimizer states are retained when switching
  to WSRL online fine-tuning.

The optional offline pre-training implementation uses the released CQL/Cal-QL
settings with the same actor/critic architecture as the WSRL checkpoint. WSRL
itself is agnostic to the offline algorithm; loading a checkpoint generated by
another faithful offline RL implementation is also supported.

PyTorch and JAX/Flax have different PRNG streams, parameter layouts, and
low-level kernels. Therefore this is an algorithmically faithful PyTorch port,
not a bitwise numerical reproduction.

Typical direct run::

    python warl.py --env_name=antmaze-umaze-v2 --train_seed=0

Environment-dependent settings are selected automatically from ``env_name`` when
``official_preset=True``. For AntMaze/MuJoCo and Adroit-Binary this follows the
released WSRL setup. For the standard D4RL Adroit human/cloned/expert tasks used
in the unified RLPD benchmark, the WSRL mechanism is retained but the dataset,
reward, termination, and evaluation protocol are adapted to standard D4RL.
General experiment controls remain available as command-line arguments.
"""

import math
import os
import random
from contextlib import contextmanager
from copy import deepcopy
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Mapping, Optional, Sequence, Tuple

os.environ.setdefault("D4RL_SUPPRESS_IMPORT_ERROR", "1")

import d4rl  # noqa: F401: registers D4RL environments
import gym
import numpy as np
import pyrallis
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.distributions import Normal
from torch.utils.tensorboard import SummaryWriter
from tqdm import trange


NumpyBatch = Dict[str, np.ndarray]
TorchBatch = Dict[str, torch.Tensor]


@dataclass
class TrainConfig:
    # ------------------------------------------------------------------
    # Environment and automatic preset
    # ------------------------------------------------------------------
    env_name: str = "antmaze-umaze-v2"
    official_preset: bool = True
    dataset_source: str = "auto"  # auto | d4rl | adroit_binary
    # Standard Adroit-v1 always resolves to d4rl; *-binary-v0 resolves separately.
    adroit_binary_data_dir: Optional[str] = None
    adroit_binary_include_bc: bool = True

    # ------------------------------------------------------------------
    # Initialization: pretrain in this file or load a compatible checkpoint
    # ------------------------------------------------------------------
    initialization_mode: str = "pretrain"  # pretrain | load
    pretrained_checkpoint: Optional[str] = None
    strict_checkpoint: bool = True
    restore_optimizer_states: bool = True

    # WSRL is offline-algorithm agnostic. Main experiments use Cal-QL for
    # AntMaze/Adroit/Kitchen and CQL for locomotion.
    offline_algorithm: str = "auto"  # auto | calql | cql
    pretrain_steps: Optional[int] = None

    # ------------------------------------------------------------------
    # Network architecture
    # ------------------------------------------------------------------
    actor_hidden_dims: Optional[Tuple[int, ...]] = None
    critic_hidden_dims: Optional[Tuple[int, ...]] = None
    std_parameterization: Optional[str] = None  # uniform | exp
    num_critics: int = 10
    online_num_min_qs: Optional[int] = None
    pretrain_num_min_qs: int = 2
    use_layer_norm: bool = True
    layer_norm_eps: float = 1e-6
    hidden_init_scale: float = math.sqrt(2.0)
    final_hidden_init_scale: float = 1e-2
    output_init_scale: float = math.sqrt(2.0)
    policy_std_min: float = 1e-5
    policy_std_max: float = 10.0

    # ------------------------------------------------------------------
    # SAC / REDQ settings
    # ------------------------------------------------------------------
    discount: float = 0.99
    tau: float = 5e-3
    actor_learning_rate: float = 1e-4
    critic_learning_rate: float = 3e-4
    temperature_learning_rate: float = 1e-4
    init_temperature: float = 1.0
    target_entropy: Optional[float] = None
    backup_entropy: bool = False

    # AntMaze WSRL uses max target backup over multiple policy actions.
    max_target_backup: Optional[bool] = None
    target_backup_n_actions: int = 10

    # ------------------------------------------------------------------
    # Offline CQL / Cal-QL initialization
    # ------------------------------------------------------------------
    cql_n_actions: int = 10
    # Official CQL/Cal-QL initialization uses its own max-target backup flag.
    # This is intentionally separate from WSRL online `max_target_backup`.
    cql_max_target_backup: bool = True
    cql_temperature: float = 1.0
    cql_importance_sample: Optional[bool] = None
    cql_alpha: Optional[float] = None
    cql_autotune_alpha: Optional[bool] = None
    cql_target_action_gap: Optional[float] = None
    cql_alpha_prime_init: float = 1.0
    cql_alpha_prime_learning_rate: float = 3e-4
    cql_clip_diff_min: float = -float("inf")
    cql_clip_diff_max: float = float("inf")
    sparse_failure_reward: Optional[float] = None

    # ------------------------------------------------------------------
    # WSRL online schedule
    # ------------------------------------------------------------------
    warmup_steps: int = 5_000
    online_steps: int = 1_000_000
    minibatch_size: int = 256
    utd_ratio: int = 4
    replay_buffer_capacity: int = 2_000_000

    # Main WSRL setting. A nonzero value is an ablation, not default WSRL.
    offline_data_ratio_online: float = 0.0

    # ------------------------------------------------------------------
    # Reward and environment handling
    # ------------------------------------------------------------------
    reward_scale: Optional[float] = None
    reward_bias: Optional[float] = None
    clip_action: float = 0.99999
    max_episode_steps: Optional[int] = None

    # ------------------------------------------------------------------
    # Evaluation, logging, and reproducibility
    # ------------------------------------------------------------------
    eval_episodes: int = 10
    eval_every: int = 5_000
    log_every: int = 5_000
    save_every: int = 100_000

    train_seed: int = 42
    eval_seed_offset: int = 1_000
    dataset_seed: Optional[int] = None
    deterministic_torch: bool = False

    checkpoints_path: Optional[str] = None
    log_root: str = "logs/WSRL_PyTorch"
    device: str = "cuda:0" if torch.cuda.is_available() else "cpu"


# -----------------------------------------------------------------------------
# Configuration
# -----------------------------------------------------------------------------


UNIFIED_D4RL_LOCOMOTION_ENVS = {
    f"{agent}-{dataset}-v2"
    for agent in ("halfcheetah", "hopper", "walker2d")
    for dataset in ("random", "medium", "medium-replay", "medium-expert")
}

UNIFIED_D4RL_ADROIT_ENVS = {
    f"{task}-{dataset}-v1"
    for task in ("pen", "door", "hammer", "relocate")
    for dataset in ("human", "cloned", "expert")
}

UNIFIED_D4RL_ANTMAZE_ENVS = {
    "antmaze-umaze-v2",
    "antmaze-umaze-diverse-v2",
    "antmaze-medium-play-v2",
    "antmaze-medium-diverse-v2",
    "antmaze-large-play-v2",
    "antmaze-large-diverse-v2",
}

OFFICIAL_ADROIT_BINARY_ENVS = {
    "pen-binary-v0",
    "door-binary-v0",
    "relocate-binary-v0",
    "pen-binary",
    "door-binary",
    "relocate-binary",
}


def _env_type(env_name: str) -> str:
    """Return the environment family used by preprocessing and evaluation.

    ``adroit_d4rl`` means the standard D4RL v1 human/cloned/expert tasks used
    in the unified RLPD/RiBES benchmark. ``adroit_binary`` means the separate
    Adroit-Binary setup used by the original WSRL paper.
    """
    name = env_name.lower()
    if name in UNIFIED_D4RL_ANTMAZE_ENVS or "antmaze" in name:
        return "antmaze"
    if name in UNIFIED_D4RL_ADROIT_ENVS:
        return "adroit_d4rl"
    if name in OFFICIAL_ADROIT_BINARY_ENVS or (
        "binary" in name and any(x in name for x in ("pen", "door", "relocate"))
    ):
        return "adroit_binary"
    if "kitchen" in name:
        return "kitchen"
    if name in UNIFIED_D4RL_LOCOMOTION_ENVS or any(
        x in name for x in ("halfcheetah", "hopper", "walker2d")
    ):
        return "locomotion"
    return "generic"


def _preset_label(env_name: str) -> str:
    env_type = _env_type(env_name)
    if env_type == "adroit_d4rl":
        return "unified_d4rl_adroit_wsrl_adaptation"
    if env_type == "adroit_binary":
        return "official_wsrl_adroit_binary"
    if env_type in {"antmaze", "locomotion", "kitchen"}:
        return "wsrl_reference"
    return "custom"


def _resolve_official_preset(config: TrainConfig) -> None:
    """Resolve environment-dependent WSRL settings.

    For standard D4RL Adroit (human/cloned/expert), this function intentionally
    uses the same D4RL task/dataset/evaluation protocol as the RLPD benchmark.
    That branch is an adaptation of WSRL to the unified benchmark, because the
    original WSRL paper used Adroit-Binary instead.

    User-controlled experimental parameters such as ``pretrain_steps`` (when
    explicitly supplied), ``online_steps``, ``eval_every``, ``eval_episodes``,
    ``save_every``, ``train_seed`` and ``device`` are not overwritten.
    """
    env_type = _env_type(config.env_name)

    if not config.official_preset:
        if config.dataset_source == "auto":
            config.dataset_source = (
                "adroit_binary" if env_type == "adroit_binary" else "d4rl"
            )
        config.dataset_source = config.dataset_source.lower()
        if config.offline_algorithm == "auto":
            config.offline_algorithm = "cql" if env_type == "locomotion" else "calql"
        config.offline_algorithm = config.offline_algorithm.lower()
        return

    if env_type == "generic":
        raise ValueError(
            f"Environment {config.env_name!r} is not covered by the automatic WSRL "
            "presets. The intended unified benchmark contains 12 MuJoCo-v2, "
            "12 standard D4RL Adroit-v1, and 6 AntMaze-v2 tasks. Set "
            "official_preset=False only for an intentional custom adaptation."
        )

    # Shared WSRL choices from the released implementation.
    config.num_critics = 10
    config.online_num_min_qs = 2
    config.pretrain_num_min_qs = 2
    config.use_layer_norm = True
    config.layer_norm_eps = 1e-6
    config.hidden_init_scale = math.sqrt(2.0)
    config.output_init_scale = math.sqrt(2.0)
    config.policy_std_min = 1e-5
    config.policy_std_max = 10.0

    # Offline CQL/Cal-QL has its own max-target-backup switch. It must not be
    # tied to the online WSRL max-target-backup switch.
    config.cql_n_actions = 10
    config.cql_max_target_backup = True
    config.cql_temperature = 1.0
    config.cql_alpha_prime_init = 1.0
    config.cql_alpha_prime_learning_rate = 3e-4
    config.cql_clip_diff_min = -float("inf")
    config.cql_clip_diff_max = float("inf")

    if env_type == "antmaze":
        config.dataset_source = "d4rl"
        config.offline_algorithm = "calql"
        config.actor_hidden_dims = (256, 256)
        config.critic_hidden_dims = (256, 256, 256, 256)
        config.final_hidden_init_scale = 1e-2
        config.std_parameterization = "uniform"
        config.max_target_backup = True
        config.target_backup_n_actions = 10
        config.reward_scale = 10.0
        config.reward_bias = -5.0
        if config.pretrain_steps is None:
            config.pretrain_steps = 1_000_000
        config.cql_importance_sample = True
        config.cql_alpha = 5.0
        config.cql_autotune_alpha = True
        config.cql_target_action_gap = 0.8
        config.sparse_failure_reward = -5.0

    elif env_type == "adroit_binary":
        config.dataset_source = "adroit_binary"
        config.offline_algorithm = "calql"
        config.actor_hidden_dims = (512, 512)
        config.critic_hidden_dims = (512, 512, 512)
        config.final_hidden_init_scale = 1e-2
        config.std_parameterization = "exp"
        config.max_target_backup = False
        config.reward_scale = 10.0
        config.reward_bias = 5.0
        if config.pretrain_steps is None:
            config.pretrain_steps = 20_000
        config.cql_importance_sample = True
        config.cql_alpha = 1.0
        config.cql_autotune_alpha = False
        config.cql_target_action_gap = 1.0
        config.sparse_failure_reward = None

        if config.adroit_binary_data_dir is None:
            data_prefix = os.environ.get(
                "DATA_DIR_PREFIX", os.path.expanduser("~/adroit_data")
            )
            config.adroit_binary_data_dir = str(
                Path(data_prefix).expanduser() / "offpolicy_hand_data"
            )

    elif env_type == "adroit_d4rl":
        # Unified benchmark adaptation. Keep WSRL's Adroit model/optimizer
        # family and Cal-QL initialization, but use standard D4RL data and raw
        # D4RL rewards. In particular, do NOT apply the Adroit-Binary +5 bias,
        # x10 scaling, success-terminal wrapper, or Binary .npy loader.
        config.dataset_source = "d4rl"
        config.offline_algorithm = "calql"
        config.actor_hidden_dims = (512, 512)
        config.critic_hidden_dims = (512, 512, 512)
        config.final_hidden_init_scale = 1e-2
        config.std_parameterization = "exp"
        config.max_target_backup = False
        config.reward_scale = 1.0
        config.reward_bias = 0.0
        if config.pretrain_steps is None:
            # Reference default inherited from the WSRL Adroit family. This is
            # an experimental budget and can be overridden from the CLI.
            config.pretrain_steps = 20_000
        config.cql_importance_sample = True
        config.cql_alpha = 1.0
        config.cql_autotune_alpha = False
        config.cql_target_action_gap = 1.0
        config.sparse_failure_reward = None

    elif env_type == "kitchen":
        config.dataset_source = "d4rl"
        config.offline_algorithm = "calql"
        config.actor_hidden_dims = (512, 512, 512)
        config.critic_hidden_dims = (512, 512, 512)
        # Official Kitchen config does not set kernel_scale_final=1e-2.
        config.final_hidden_init_scale = math.sqrt(2.0)
        config.std_parameterization = "exp"
        config.max_target_backup = False
        config.reward_scale = 1.0
        config.reward_bias = -4.0
        if config.pretrain_steps is None:
            config.pretrain_steps = 250_000
        config.cql_importance_sample = False
        config.cql_alpha = 5.0
        config.cql_autotune_alpha = False
        config.cql_target_action_gap = 1.0
        config.sparse_failure_reward = None

    elif env_type == "locomotion":
        config.dataset_source = "d4rl"
        config.offline_algorithm = "cql"
        config.actor_hidden_dims = (256, 256)
        config.critic_hidden_dims = (256, 256)
        config.final_hidden_init_scale = 1e-2
        config.std_parameterization = "exp"
        config.max_target_backup = False
        config.reward_scale = 1.0
        config.reward_bias = 0.0
        if config.pretrain_steps is None:
            config.pretrain_steps = 250_000
        config.cql_importance_sample = True
        config.cql_alpha = 5.0
        config.cql_autotune_alpha = False
        config.cql_target_action_gap = 1.0
        config.sparse_failure_reward = None

    config.dataset_source = config.dataset_source.lower()
    config.offline_algorithm = config.offline_algorithm.lower()

def _validate_config(config: TrainConfig) -> None:
    if config.initialization_mode not in {"pretrain", "load"}:
        raise ValueError("initialization_mode must be 'pretrain' or 'load'.")
    if config.offline_algorithm not in {"cql", "calql"}:
        raise ValueError("offline_algorithm must be 'cql' or 'calql'.")
    if config.initialization_mode == "load" and not config.pretrained_checkpoint:
        raise ValueError("pretrained_checkpoint is required when initialization_mode='load'.")
    if config.num_critics < 1:
        raise ValueError("num_critics must be positive.")
    for value, name in (
        (config.pretrain_num_min_qs, "pretrain_num_min_qs"),
        (int(config.online_num_min_qs), "online_num_min_qs"),
    ):
        if value < 1 or value > config.num_critics:
            raise ValueError(f"{name} must be in [1, num_critics].")
    if config.minibatch_size < 1 or config.utd_ratio < 1:
        raise ValueError("minibatch_size and utd_ratio must be positive.")
    if config.cql_n_actions < 1 or config.target_backup_n_actions < 1:
        raise ValueError("cql_n_actions and target_backup_n_actions must be positive.")
    if config.warmup_steps < config.minibatch_size * config.utd_ratio:
        raise ValueError(
            "warmup_steps must be at least minibatch_size * utd_ratio so the "
            "first WSRL update can sample a complete online super-batch."
        )
    if not math.isclose(config.offline_data_ratio_online, 0.0, abs_tol=1e-12):
        raise ValueError(
            "This file implements the main no-retention WSRL setting. "
            "offline_data_ratio_online must be 0.0."
        )
    if config.std_parameterization not in {"uniform", "exp"}:
        raise ValueError("std_parameterization must be 'uniform' or 'exp'.")
    if config.dataset_source not in {"d4rl", "adroit_binary"}:
        raise ValueError("dataset_source must be 'd4rl' or 'adroit_binary'.")


# -----------------------------------------------------------------------------
# Environment compatibility
# -----------------------------------------------------------------------------


def _convert_observation_to_float32(observation):
    if isinstance(observation, np.ndarray) and observation.dtype == np.float64:
        return observation.astype(np.float32)
    if isinstance(observation, dict):
        return {k: _convert_observation_to_float32(v) for k, v in observation.items()}
    return observation


class SinglePrecision(gym.ObservationWrapper):
    def __init__(self, env: gym.Env):
        super().__init__(env)
        space = env.observation_space
        if isinstance(space, gym.spaces.Box):
            self.observation_space = gym.spaces.Box(
                low=space.low,
                high=space.high,
                shape=space.shape,
                dtype=np.float32,
            )
        elif isinstance(space, gym.spaces.Dict):
            converted = {}
            for key, subspace in space.spaces.items():
                if not isinstance(subspace, gym.spaces.Box):
                    raise NotImplementedError("Only Box entries are supported.")
                converted[key] = gym.spaces.Box(
                    low=subspace.low,
                    high=subspace.high,
                    shape=subspace.shape,
                    dtype=np.float32,
                )
            self.observation_space = gym.spaces.Dict(converted)
        else:
            raise NotImplementedError(f"Unsupported observation space: {type(space)}")

    def observation(self, observation):
        return _convert_observation_to_float32(observation)


class RewardTransform(gym.RewardWrapper):
    def __init__(self, env: gym.Env, scale: float, bias: float):
        super().__init__(env)
        self.scale = float(scale)
        self.bias = float(bias)

    def reward(self, reward):
        return float(reward) * self.scale + self.bias


class UniversalSeed(gym.Wrapper):
    def seed(self, seed: int):
        result = None
        try:
            result = self.env.seed(seed)
        except Exception:
            pass
        try:
            self.env.observation_space.seed(seed)
            self.env.action_space.seed(seed)
        except Exception:
            pass
        return result


class AdroitTerminalWrapper(gym.Wrapper):
    """Match the released WSRL Adroit-Binary success termination rule only."""

    def step(self, action):
        output = self.env.step(action)
        if len(output) == 5:
            observation, reward, terminated, truncated, info = output
            if bool(info.get("goal_achieved", False)):
                terminated = True
            return observation, reward, terminated, truncated, info
        observation, reward, done, info = output
        if bool(info.get("goal_achieved", False)):
            done = True
        return observation, reward, done, info


class KitchenTerminalWrapper(gym.Wrapper):
    """Match the released WSRL Kitchen completion termination rule."""

    def step(self, action):
        output = self.env.step(action)
        if len(output) == 5:
            observation, reward, terminated, truncated, info = output
            if float(reward) == 4.0:
                terminated = True
            return observation, reward, terminated, truncated, info
        observation, reward, done, info = output
        if float(reward) == 4.0:
            done = True
        return observation, reward, done, info


def wrap_env(env: gym.Env, config: TrainConfig, training: bool) -> gym.Env:
    env_type = _env_type(config.env_name)

    # Released WSRL applies these terminal fixes immediately after gym.make().
    if env_type == "adroit_binary":
        env = AdroitTerminalWrapper(env)
    elif env_type == "kitchen":
        env = KitchenTerminalWrapper(env)

    env = SinglePrecision(env)
    env = UniversalSeed(env)
    if env_type in {"antmaze", "kitchen", "locomotion", "adroit_d4rl"}:
        # Standard D4RL Adroit follows the same rescaled-action interface used
        # by the RLPD benchmark; official Adroit-Binary keeps its released path.
        # Match released make_gym_env for the other WSRL domains: expose the policy action space as
        # [-clip_action, clip_action], then rescale to the base env bounds.
        env = gym.wrappers.RescaleAction(
            env, -float(config.clip_action), float(config.clip_action)
        )
    if isinstance(env.observation_space, gym.spaces.Dict):
        env = gym.wrappers.FlattenObservation(env)
    if env_type in {"antmaze", "kitchen", "locomotion", "adroit_d4rl"}:
        env = gym.wrappers.ClipAction(env)
    if training:
        env = RewardTransform(env, float(config.reward_scale), float(config.reward_bias))
    try:
        env = gym.wrappers.RecordEpisodeStatistics(env)
    except Exception:
        pass
    return env


def _seed_env(env: gym.Env, seed: int) -> None:
    try:
        env.seed(seed)
    except Exception:
        try:
            env.reset(seed=seed)
        except Exception:
            pass
    try:
        env.action_space.seed(seed)
        env.observation_space.seed(seed)
    except Exception:
        pass


def _reset_env(env: gym.Env, seed: Optional[int] = None):
    try:
        output = env.reset(seed=seed) if seed is not None else env.reset()
    except TypeError:
        if seed is not None:
            _seed_env(env, seed)
        output = env.reset()
    return output[0] if isinstance(output, tuple) else output


def _step_env(env: gym.Env, action):
    output = env.step(action)
    if len(output) == 5:
        next_observation, reward, terminated, truncated, info = output
        return (
            next_observation,
            float(reward),
            bool(terminated),
            bool(truncated),
            dict(info),
        )
    next_observation, reward, done, info = output
    info = dict(info)
    truncated = bool(info.get("TimeLimit.truncated", False))
    terminated = bool(done and not truncated)
    return next_observation, float(reward), terminated, truncated, info


def _max_episode_steps(env: gym.Env, override: Optional[int]) -> int:
    if override is not None:
        return int(override)
    candidate = env
    for _ in range(16):
        value = getattr(candidate, "_max_episode_steps", None)
        if value is not None:
            return int(value)
        spec = getattr(candidate, "spec", None)
        if spec is not None and getattr(spec, "max_episode_steps", None) is not None:
            return int(spec.max_episode_steps)
        if not hasattr(candidate, "env"):
            break
        candidate = candidate.env
    return 1_000


# -----------------------------------------------------------------------------
# Offline datasets and online replay buffer
# -----------------------------------------------------------------------------


def _discounted_return_to_go(
    rewards: np.ndarray,
    terminals: np.ndarray,
    discount: float,
    sparse_failure_reward: Optional[float],
) -> np.ndarray:
    rewards = np.asarray(rewards, dtype=np.float32).reshape(-1)
    terminals = np.asarray(terminals, dtype=np.float32).reshape(-1)
    if rewards.shape != terminals.shape:
        raise ValueError("rewards and terminals must have identical shapes.")
    if rewards.size == 0:
        return rewards.copy()

    # Released Cal-QL sparse loader uses the infinite-horizon failure return.
    if sparse_failure_reward is not None and np.allclose(
        rewards, sparse_failure_reward, atol=1e-6, rtol=0.0
    ):
        return np.full_like(
            rewards,
            float(sparse_failure_reward) / (1.0 - float(discount)),
            dtype=np.float32,
        )

    returns = np.empty_like(rewards, dtype=np.float32)
    accumulator = 0.0
    for index in range(len(rewards) - 1, -1, -1):
        accumulator = float(rewards[index]) + float(discount) * accumulator * (
            1.0 - float(terminals[index])
        )
        returns[index] = accumulator
    return returns


def _episode_to_arrays(
    observations: Sequence[np.ndarray],
    actions: Sequence[np.ndarray],
    rewards: Sequence[float],
    next_observations: Sequence[np.ndarray],
    terminals: Sequence[bool],
    config: TrainConfig,
) -> NumpyBatch:
    transformed_rewards = (
        np.asarray(rewards, dtype=np.float32) * float(config.reward_scale)
        + float(config.reward_bias)
    )
    terminals_array = np.asarray(terminals, dtype=np.float32)
    mc_returns = _discounted_return_to_go(
        transformed_rewards,
        terminals_array,
        config.discount,
        config.sparse_failure_reward,
    )
    return {
        "observations": np.asarray(observations, dtype=np.float32),
        "actions": np.clip(
            np.asarray(actions, dtype=np.float32),
            -config.clip_action,
            config.clip_action,
        ),
        "rewards": transformed_rewards,
        "masks": 1.0 - terminals_array,
        "dones": terminals_array.astype(bool),
        "next_observations": np.asarray(next_observations, dtype=np.float32),
        "mc_returns": mc_returns,
    }


def _concatenate_batches(batches: Sequence[NumpyBatch]) -> NumpyBatch:
    nonempty = [batch for batch in batches if len(batch["rewards"]) > 0]
    if not nonempty:
        raise ValueError("Dataset loader produced no transitions.")
    return {
        key: np.concatenate([batch[key] for batch in nonempty], axis=0)
        for key in nonempty[0]
    }


def _load_standard_adroit_d4rl_dataset(
    env: gym.Env, config: TrainConfig
) -> NumpyBatch:
    """Load standard D4RL Adroit with RLPD-compatible qlearning semantics.

    RLPD's D4RL path uses ``d4rl.qlearning_dataset``. We use the same
    transition set for pen/door/hammer/relocate human/cloned/expert and then
    reconstruct trajectory boundaries so Cal-QL can obtain Monte-Carlo returns.
    """
    candidate = env
    for _ in range(16):
        if hasattr(candidate, "get_dataset"):
            break
        if not hasattr(candidate, "env"):
            break
        candidate = candidate.env
    if not hasattr(candidate, "get_dataset"):
        raise AttributeError("The standard D4RL Adroit environment has no get_dataset().")

    raw = d4rl.qlearning_dataset(candidate)
    observations = np.asarray(raw["observations"], dtype=np.float32)
    actions = np.asarray(raw["actions"], dtype=np.float32)
    rewards = np.asarray(raw["rewards"], dtype=np.float32).reshape(-1)
    terminals = np.asarray(raw["terminals"], dtype=np.float32).reshape(-1)
    next_observations = np.asarray(raw["next_observations"], dtype=np.float32)

    if not (
        len(observations)
        == len(actions)
        == len(rewards)
        == len(terminals)
        == len(next_observations)
    ):
        raise ValueError("D4RL qlearning_dataset fields have inconsistent lengths.")

    # This is the same discontinuity test used by the local RLPD baseline to
    # recover episode boundaries after d4rl.qlearning_dataset filters timeouts.
    boundaries = np.zeros(len(rewards), dtype=bool)
    if len(rewards) > 1:
        diffs = np.linalg.norm(
            observations[1:] - next_observations[:-1], axis=-1
        )
        boundaries[:-1] = np.logical_or(diffs > 1e-6, terminals[:-1] > 0.5)
    if len(rewards) > 0:
        boundaries[-1] = True

    episodes: List[NumpyBatch] = []
    start = 0
    for index, is_boundary in enumerate(boundaries):
        if not is_boundary:
            continue
        end = index + 1
        episodes.append(
            _episode_to_arrays(
                observations[start:end],
                actions[start:end],
                rewards[start:end],
                next_observations[start:end],
                terminals[start:end] > 0.5,
                config,
            )
        )
        start = end

    return _concatenate_batches(episodes)


def _load_d4rl_dataset(env: gym.Env, config: TrainConfig) -> NumpyBatch:
    if _env_type(config.env_name) == "adroit_d4rl":
        return _load_standard_adroit_d4rl_dataset(env, config)

    candidate = env
    raw_dataset = None
    for _ in range(16):
        if hasattr(candidate, "get_dataset"):
            raw_dataset = candidate.get_dataset()
            break
        if not hasattr(candidate, "env"):
            break
        candidate = candidate.env
    if raw_dataset is None:
        raise AttributeError("The environment does not expose get_dataset().")

    observations = np.asarray(raw_dataset["observations"])
    actions = np.asarray(raw_dataset["actions"])
    rewards = np.asarray(raw_dataset["rewards"])
    terminals = np.asarray(raw_dataset["terminals"]).astype(bool)
    timeouts = (
        np.asarray(raw_dataset["timeouts"]).astype(bool)
        if "timeouts" in raw_dataset
        else None
    )
    next_observations_raw = raw_dataset.get("next_observations")
    horizon = _max_episode_steps(env, config.max_episode_steps)

    episodes: List[NumpyBatch] = []
    ep_obs: List[np.ndarray] = []
    ep_actions: List[np.ndarray] = []
    ep_rewards: List[float] = []
    ep_next_obs: List[np.ndarray] = []
    ep_terminals: List[bool] = []
    episode_step = 0

    for index in range(len(rewards)):
        timeout = (
            bool(timeouts[index])
            if timeouts is not None
            else episode_step == horizon - 1
        )
        terminal = bool(terminals[index])

        # Match the released loader: timeout transitions are not included.
        if not timeout and index != len(rewards) - 1:
            ep_obs.append(observations[index])
            ep_actions.append(actions[index])
            ep_rewards.append(float(rewards[index]))
            if next_observations_raw is not None:
                ep_next_obs.append(next_observations_raw[index])
            else:
                ep_next_obs.append(observations[index + 1])
            ep_terminals.append(terminal)

        episode_step += 1
        if terminal or timeout or index == len(rewards) - 1:
            if ep_rewards:
                episodes.append(
                    _episode_to_arrays(
                        ep_obs,
                        ep_actions,
                        ep_rewards,
                        ep_next_obs,
                        ep_terminals,
                        config,
                    )
                )
            ep_obs, ep_actions, ep_rewards = [], [], []
            ep_next_obs, ep_terminals = [], []
            episode_step = 0

    return _concatenate_batches(episodes)


def _binary_file_candidates(env_name: str, include_bc: bool) -> List[str]:
    name = env_name.lower()
    if "pen" in name:
        expert, bc = "pen2_sparse.npy", "pen_bc_sparse4.npy"
    elif "door" in name:
        expert, bc = "door2_sparse.npy", "door_bc_sparse4.npy"
    elif "relocate" in name:
        expert, bc = "relocate2_sparse.npy", "relocate_bc_sparse4.npy"
    else:
        raise ValueError("Adroit-Binary supports Pen, Door, and Relocate.")
    return [expert, bc] if include_bc else [expert]


def _extract_trajectory_field(trajectory, names: Sequence[str]):
    if isinstance(trajectory, Mapping):
        for name in names:
            if name in trajectory:
                return trajectory[name]
    for name in names:
        if hasattr(trajectory, name):
            return getattr(trajectory, name)
    raise KeyError(f"None of the fields {tuple(names)} were found.")


def _state_observation_array(values) -> np.ndarray:
    states = []
    for value in values:
        if isinstance(value, Mapping):
            value = value["state_observation"]
        states.append(np.asarray(value, dtype=np.float32))
    return np.asarray(states, dtype=np.float32)


def _load_adroit_binary_dataset(config: TrainConfig) -> NumpyBatch:
    if config.adroit_binary_data_dir is None:
        raise ValueError(
            "adroit_binary_data_dir must point to the downloaded "
            "offpolicy_hand_data directory."
        )
    root = Path(config.adroit_binary_data_dir)
    paths = [
        root / filename
        for filename in _binary_file_candidates(
            config.env_name, config.adroit_binary_include_bc
        )
    ]
    missing = [str(path) for path in paths if not path.exists()]
    if missing:
        raise FileNotFoundError("Missing Adroit data: " + ", ".join(missing))

    episodes: List[NumpyBatch] = []
    for path in paths:
        trajectories = np.load(path, allow_pickle=True)
        for trajectory in trajectories:
            if isinstance(trajectory, np.ndarray) and trajectory.shape == ():
                trajectory = trajectory.item()
            observations = _state_observation_array(
                _extract_trajectory_field(trajectory, ("observations", "observations_n"))
            )
            actions = np.asarray(
                _extract_trajectory_field(trajectory, ("actions",)), dtype=np.float32
            )
            rewards = np.asarray(
                _extract_trajectory_field(trajectory, ("rewards",)), dtype=np.float32
            ).squeeze()
            success_indices = np.flatnonzero(np.isclose(rewards, 0.0))
            if success_indices.size == 0:
                continue
            last = int(success_indices[-1])
            try:
                next_observations = _state_observation_array(
                    _extract_trajectory_field(
                        trajectory, ("next_observations", "next_observations_n")
                    )
                )
                current_obs = observations[: last + 1]
                next_obs = next_observations[: last + 1]
            except KeyError:
                current_obs = observations[: last + 1]
                next_obs = observations[1 : last + 2]
            kept_rewards = rewards[: last + 1]
            terminals = np.isclose(kept_rewards, 0.0)
            episodes.append(
                _episode_to_arrays(
                    current_obs,
                    actions[: last + 1],
                    kept_rewards,
                    next_obs,
                    terminals,
                    config,
                )
            )
    return _concatenate_batches(episodes)


class ArrayDataset:
    def __init__(self, arrays: Mapping[str, np.ndarray], seed: Optional[int] = None):
        lengths = {len(value) for value in arrays.values()}
        if not arrays or len(lengths) != 1:
            raise ValueError("Dataset fields must be nonempty and equal length.")
        self.arrays = {key: np.asarray(value) for key, value in arrays.items()}
        self.size = int(lengths.pop())
        self._np_random, self.seed_value = gym.utils.seeding.np_random(seed)

    def sample(self, batch_size: int) -> NumpyBatch:
        if hasattr(self._np_random, "integers"):
            indices = self._np_random.integers(self.size, size=batch_size)
        else:
            indices = self._np_random.randint(self.size, size=batch_size)
        return {key: value[indices] for key, value in self.arrays.items()}


class ReplayBuffer:
    def __init__(
        self,
        observation_space: gym.Space,
        action_space: gym.Space,
        capacity: int,
        seed: Optional[int] = None,
    ):
        if not isinstance(observation_space, gym.spaces.Box):
            raise TypeError("ReplayBuffer requires a flat Box observation space.")
        if not isinstance(action_space, gym.spaces.Box):
            raise TypeError("ReplayBuffer requires a Box action space.")
        self.capacity = int(capacity)
        self.size = 0
        self.insert_index = 0
        self.observations = np.empty(
            (capacity, *observation_space.shape), dtype=np.float32
        )
        self.next_observations = np.empty_like(self.observations)
        self.actions = np.empty((capacity, *action_space.shape), dtype=np.float32)
        self.rewards = np.empty((capacity,), dtype=np.float32)
        self.masks = np.empty((capacity,), dtype=np.float32)
        self.dones = np.empty((capacity,), dtype=bool)
        self._np_random, self.seed_value = gym.utils.seeding.np_random(seed)

    def insert(
        self,
        observation: np.ndarray,
        action: np.ndarray,
        reward: float,
        mask: float,
        done: bool,
        next_observation: np.ndarray,
    ) -> None:
        index = self.insert_index
        self.observations[index] = observation
        self.actions[index] = action
        self.rewards[index] = reward
        self.masks[index] = mask
        self.dones[index] = done
        self.next_observations[index] = next_observation
        self.insert_index = (index + 1) % self.capacity
        self.size = min(self.size + 1, self.capacity)

    def sample(self, batch_size: int) -> NumpyBatch:
        if self.size == 0:
            raise ValueError("Cannot sample from an empty replay buffer.")
        if hasattr(self._np_random, "integers"):
            indices = self._np_random.integers(self.size, size=batch_size)
        else:
            indices = self._np_random.randint(self.size, size=batch_size)
        return {
            "observations": self.observations[indices],
            "actions": self.actions[indices],
            "rewards": self.rewards[indices],
            "masks": self.masks[indices],
            "dones": self.dones[indices],
            "next_observations": self.next_observations[indices],
        }


# -----------------------------------------------------------------------------
# Networks
# -----------------------------------------------------------------------------


def _init_linear_orthogonal(layer: nn.Linear, scale: float) -> None:
    nn.init.orthogonal_(layer.weight, gain=float(scale))
    if layer.bias is not None:
        nn.init.zeros_(layer.bias)


class NormalizedMLP(nn.Module):
    def __init__(
        self,
        input_dim: int,
        hidden_dims: Sequence[int],
        use_layer_norm: bool,
        layer_norm_eps: float,
        hidden_init_scale: float,
        final_hidden_init_scale: float,
    ):
        super().__init__()
        self.layers = nn.ModuleList()
        self.norms = nn.ModuleList()
        current_dim = input_dim
        for index, hidden_dim in enumerate(hidden_dims):
            layer = nn.Linear(current_dim, hidden_dim)
            scale = (
                final_hidden_init_scale
                if index == len(hidden_dims) - 1
                else hidden_init_scale
            )
            _init_linear_orthogonal(layer, scale)
            self.layers.append(layer)
            if use_layer_norm:
                self.norms.append(nn.LayerNorm(hidden_dim, eps=layer_norm_eps))
            current_dim = hidden_dim
        self.use_layer_norm = bool(use_layer_norm)
        self.output_dim = current_dim

    def forward(self, inputs: torch.Tensor) -> torch.Tensor:
        values = inputs
        for index, layer in enumerate(self.layers):
            values = layer(values)
            if self.use_layer_norm:
                values = self.norms[index](values)
            values = F.relu(values)
        return values


class TanhGaussianActor(nn.Module):
    def __init__(
        self,
        observation_dim: int,
        action_dim: int,
        hidden_dims: Sequence[int],
        std_parameterization: str,
        config: TrainConfig,
    ):
        super().__init__()
        self.trunk = NormalizedMLP(
            observation_dim,
            hidden_dims,
            config.use_layer_norm,
            config.layer_norm_eps,
            config.hidden_init_scale,
            config.final_hidden_init_scale,
        )
        self.mean = nn.Linear(self.trunk.output_dim, action_dim)
        _init_linear_orthogonal(self.mean, config.output_init_scale)
        self.std_parameterization = std_parameterization
        if std_parameterization == "exp":
            self.log_std_head = nn.Linear(self.trunk.output_dim, action_dim)
            _init_linear_orthogonal(self.log_std_head, config.output_init_scale)
            self.log_stds = None
        elif std_parameterization == "uniform":
            self.log_std_head = None
            self.log_stds = nn.Parameter(torch.zeros(action_dim))
        else:
            raise ValueError(f"Unsupported std_parameterization: {std_parameterization}")
        self.std_min = float(config.policy_std_min)
        self.std_max = float(config.policy_std_max)

    def distribution(self, observations: torch.Tensor) -> Normal:
        features = self.trunk(observations)
        mean = self.mean(features)
        if self.log_std_head is not None:
            std = self.log_std_head(features).exp()
        else:
            std = self.log_stds.exp().expand_as(mean)
        std = std.clamp(self.std_min, self.std_max)
        return Normal(mean, std)

    @staticmethod
    def _log_prob_from_pre_tanh(
        distribution: Normal, pre_tanh: torch.Tensor
    ) -> torch.Tensor:
        base_log_prob = distribution.log_prob(pre_tanh)
        correction = 2.0 * (
            math.log(2.0) - pre_tanh - F.softplus(-2.0 * pre_tanh)
        )
        return (base_log_prob - correction).sum(dim=-1)

    def sample(
        self,
        observations: torch.Tensor,
        repeat: Optional[int] = None,
        reparameterize: bool = True,
    ) -> Tuple[torch.Tensor, torch.Tensor]:
        if repeat is not None:
            observations = observations.unsqueeze(1).expand(
                observations.shape[0], repeat, observations.shape[-1]
            )
        distribution = self.distribution(observations)
        pre_tanh = (
            distribution.rsample() if reparameterize else distribution.sample()
        )
        actions = torch.tanh(pre_tanh)
        log_prob = self._log_prob_from_pre_tanh(distribution, pre_tanh)
        return actions, log_prob

    def mode(self, observations: torch.Tensor) -> torch.Tensor:
        return torch.tanh(self.distribution(observations).mean)

    @torch.no_grad()
    def sample_action(self, observation: np.ndarray, device: torch.device) -> np.ndarray:
        tensor = torch.as_tensor(
            observation, dtype=torch.float32, device=device
        ).unsqueeze(0)
        action, _ = self.sample(tensor, reparameterize=False)
        return action.squeeze(0).cpu().numpy()

    @torch.no_grad()
    def eval_action(self, observation: np.ndarray, device: torch.device) -> np.ndarray:
        tensor = torch.as_tensor(
            observation, dtype=torch.float32, device=device
        ).unsqueeze(0)
        return self.mode(tensor).squeeze(0).cpu().numpy()


class EnsembleLinear(nn.Module):
    """Independent dense layers evaluated as one vectorized ensemble."""

    def __init__(
        self,
        ensemble_size: int,
        input_dim: int,
        output_dim: int,
        init_scale: float,
    ):
        super().__init__()
        self.weight = nn.Parameter(
            torch.empty(ensemble_size, input_dim, output_dim)
        )
        self.bias = nn.Parameter(torch.zeros(ensemble_size, output_dim))
        for ensemble_index in range(ensemble_size):
            temporary = torch.empty(output_dim, input_dim)
            nn.init.orthogonal_(temporary, gain=float(init_scale))
            with torch.no_grad():
                self.weight[ensemble_index].copy_(temporary.transpose(0, 1))

    def forward_first(
        self,
        inputs: torch.Tensor,
        indices: Optional[torch.Tensor] = None,
    ) -> torch.Tensor:
        """Map ``[B,...,I]`` to ``[E,B,...,O]``."""
        weight = self.weight if indices is None else self.weight.index_select(0, indices)
        bias = self.bias if indices is None else self.bias.index_select(0, indices)
        values = torch.einsum("b...i,eio->eb...o", inputs, weight)
        view_shape = (bias.shape[0],) + (1,) * (values.ndim - 2) + (bias.shape[-1],)
        return values + bias.view(view_shape)

    def forward_ensemble(
        self,
        inputs: torch.Tensor,
        indices: Optional[torch.Tensor] = None,
    ) -> torch.Tensor:
        """Map ``[E,B,...,I]`` to ``[E,B,...,O]``."""
        weight = self.weight if indices is None else self.weight.index_select(0, indices)
        bias = self.bias if indices is None else self.bias.index_select(0, indices)
        values = torch.einsum("eb...i,eio->eb...o", inputs, weight)
        view_shape = (bias.shape[0],) + (1,) * (values.ndim - 2) + (bias.shape[-1],)
        return values + bias.view(view_shape)


class EnsembleLayerNorm(nn.Module):
    def __init__(self, ensemble_size: int, feature_dim: int, eps: float):
        super().__init__()
        self.weight = nn.Parameter(torch.ones(ensemble_size, feature_dim))
        self.bias = nn.Parameter(torch.zeros(ensemble_size, feature_dim))
        self.eps = float(eps)

    def forward(
        self,
        inputs: torch.Tensor,
        indices: Optional[torch.Tensor] = None,
    ) -> torch.Tensor:
        weight = self.weight if indices is None else self.weight.index_select(0, indices)
        bias = self.bias if indices is None else self.bias.index_select(0, indices)
        mean = inputs.mean(dim=-1, keepdim=True)
        variance = (inputs - mean).pow(2).mean(dim=-1, keepdim=True)
        normalized = (inputs - mean) * torch.rsqrt(variance + self.eps)
        view_shape = (weight.shape[0],) + (1,) * (inputs.ndim - 2) + (weight.shape[-1],)
        return normalized * weight.view(view_shape) + bias.view(view_shape)


class CriticEnsemble(nn.Module):
    def __init__(
        self,
        observation_dim: int,
        action_dim: int,
        hidden_dims: Sequence[int],
        ensemble_size: int,
        config: TrainConfig,
    ):
        super().__init__()
        self.ensemble_size = int(ensemble_size)
        self.hidden_layers = nn.ModuleList()
        self.layer_norms = nn.ModuleList()
        input_dim = observation_dim + action_dim
        for layer_index, hidden_dim in enumerate(hidden_dims):
            init_scale = (
                config.final_hidden_init_scale
                if layer_index == len(hidden_dims) - 1
                else config.hidden_init_scale
            )
            self.hidden_layers.append(
                EnsembleLinear(
                    self.ensemble_size,
                    input_dim,
                    hidden_dim,
                    init_scale,
                )
            )
            if config.use_layer_norm:
                self.layer_norms.append(
                    EnsembleLayerNorm(
                        self.ensemble_size,
                        hidden_dim,
                        config.layer_norm_eps,
                    )
                )
            input_dim = hidden_dim
        self.output_layer = EnsembleLinear(
            self.ensemble_size,
            input_dim,
            1,
            config.output_init_scale,
        )
        self.use_layer_norm = bool(config.use_layer_norm)

    def forward(
        self,
        observations: torch.Tensor,
        actions: torch.Tensor,
        indices: Optional[torch.Tensor] = None,
    ) -> torch.Tensor:
        if actions.ndim == observations.ndim + 1:
            observations = observations.unsqueeze(1).expand(
                observations.shape[0], actions.shape[1], observations.shape[-1]
            )
        values = torch.cat([observations, actions], dim=-1)
        for layer_index, layer in enumerate(self.hidden_layers):
            if layer_index == 0:
                values = layer.forward_first(values, indices=indices)
            else:
                values = layer.forward_ensemble(values, indices=indices)
            if self.use_layer_norm:
                values = self.layer_norms[layer_index](values, indices=indices)
            values = F.relu(values)
        values = self.output_layer.forward_ensemble(values, indices=indices)
        return values.squeeze(-1)


# -----------------------------------------------------------------------------
# WSRL learner with optional CQL/Cal-QL initialization
# -----------------------------------------------------------------------------


@contextmanager
def _frozen_parameters(module: nn.Module):
    parameters = list(module.parameters())
    previous = [parameter.requires_grad for parameter in parameters]
    try:
        for parameter in parameters:
            parameter.requires_grad_(False)
        yield
    finally:
        for parameter, requires_grad in zip(parameters, previous):
            parameter.requires_grad_(requires_grad)


def _soft_update(target: nn.Module, source: nn.Module, tau: float) -> None:
    with torch.no_grad():
        for target_parameter, source_parameter in zip(
            target.parameters(), source.parameters()
        ):
            target_parameter.mul_(1.0 - tau).add_(source_parameter, alpha=tau)


def _inverse_softplus(value: float) -> float:
    return math.log(math.expm1(float(value)))


class WSRLLearner:
    def __init__(
        self,
        actor: TanhGaussianActor,
        critic: CriticEnsemble,
        action_dim: int,
        config: TrainConfig,
        device: torch.device,
    ):
        self.actor = actor
        self.critic = critic
        self.target_critic = deepcopy(critic).to(device)
        self.target_critic.requires_grad_(False)
        self.config = config
        self.device = device
        self.action_dim = int(action_dim)

        self.actor_optimizer = torch.optim.Adam(
            self.actor.parameters(), lr=config.actor_learning_rate
        )
        self.critic_optimizer = torch.optim.Adam(
            self.critic.parameters(), lr=config.critic_learning_rate
        )

        self.raw_temperature = torch.tensor(
            _inverse_softplus(config.init_temperature),
            dtype=torch.float32,
            device=device,
            requires_grad=True,
        )
        self.temperature_optimizer = torch.optim.Adam(
            [self.raw_temperature], lr=config.temperature_learning_rate
        )

        self.raw_cql_alpha_prime: Optional[torch.Tensor]
        self.cql_alpha_prime_optimizer: Optional[torch.optim.Optimizer]
        if bool(config.cql_autotune_alpha):
            self.raw_cql_alpha_prime = torch.tensor(
                _inverse_softplus(config.cql_alpha_prime_init),
                dtype=torch.float32,
                device=device,
                requires_grad=True,
            )
            self.cql_alpha_prime_optimizer = torch.optim.Adam(
                [self.raw_cql_alpha_prime],
                lr=config.cql_alpha_prime_learning_rate,
            )
        else:
            self.raw_cql_alpha_prime = None
            self.cql_alpha_prime_optimizer = None

        self.target_entropy = (
            -float(action_dim)
            if config.target_entropy is None or config.target_entropy >= 0.0
            else float(config.target_entropy)
        )
        self.num_min_qs = int(config.pretrain_num_min_qs)
        self.max_target_backup = bool(config.max_target_backup)

    @property
    def temperature(self) -> torch.Tensor:
        return F.softplus(self.raw_temperature)

    @property
    def cql_alpha_prime(self) -> Optional[torch.Tensor]:
        if self.raw_cql_alpha_prime is None:
            return None
        return F.softplus(self.raw_cql_alpha_prime)

    def switch_to_online_wsrl(self) -> None:
        self.num_min_qs = int(self.config.online_num_min_qs)
        self.max_target_backup = bool(self.config.max_target_backup)

    def _sample_target_indices(self) -> Optional[torch.Tensor]:
        if self.num_min_qs >= self.critic.ensemble_size:
            return None
        # Official JAX code uses randint, so sampling is with replacement.
        return torch.randint(
            low=0,
            high=self.critic.ensemble_size,
            size=(self.num_min_qs,),
            device=self.device,
        )

    def _target_q(
        self,
        batch: TorchBatch,
        *,
        max_target_backup: Optional[bool] = None,
        n_backup_actions: Optional[int] = None,
    ) -> torch.Tensor:
        """Compute the SAC target with released WSRL/CQL backup semantics.

        Online WSRL uses ``self.max_target_backup`` (True only for AntMaze).
        Offline CQL/Cal-QL instead passes ``cql_max_target_backup=True`` and
        ``cql_n_actions=10`` regardless of the online setting.
        """
        use_max_backup = (
            self.max_target_backup
            if max_target_backup is None
            else bool(max_target_backup)
        )
        if n_backup_actions is None:
            n_backup_actions = self.config.target_backup_n_actions

        with torch.no_grad():
            indices = self._sample_target_indices()
            if use_max_backup:
                next_actions, next_log_probs = self.actor.sample(
                    batch["next_observations"],
                    repeat=int(n_backup_actions),
                    reparameterize=False,
                )
                target_next_qs = self.target_critic(
                    batch["next_observations"], next_actions, indices=indices
                )
                # Released code: subsample critics -> min across critics -> max
                # across the sampled next actions.
                target_next_q = target_next_qs.min(dim=0).values
                max_indices = target_next_q.argmax(dim=-1, keepdim=True)
                target_next_q = target_next_q.gather(-1, max_indices).squeeze(-1)
                selected_log_prob = next_log_probs.gather(
                    -1, max_indices
                ).squeeze(-1)
                if self.config.backup_entropy:
                    target_next_q = (
                        target_next_q
                        - self.temperature.detach() * selected_log_prob
                    )
            else:
                next_actions, next_log_prob = self.actor.sample(
                    batch["next_observations"], reparameterize=False
                )
                target_next_qs = self.target_critic(
                    batch["next_observations"], next_actions, indices=indices
                )
                target_next_q = target_next_qs.min(dim=0).values
                if self.config.backup_entropy:
                    target_next_q = (
                        target_next_q
                        - self.temperature.detach() * next_log_prob
                    )

            return (
                batch["rewards"]
                + self.config.discount * batch["masks"] * target_next_q
            )

    def update_critic(self, batch: TorchBatch) -> Dict[str, float]:
        target_q = self._target_q(batch)
        predicted_qs = self.critic(batch["observations"], batch["actions"])
        critic_loss = (predicted_qs - target_q.unsqueeze(0)).pow(2).mean()

        self.critic_optimizer.zero_grad(set_to_none=True)
        critic_loss.backward()
        self.critic_optimizer.step()
        _soft_update(self.target_critic, self.critic, self.config.tau)

        return {
            "critic_loss": float(critic_loss.detach().item()),
            "predicted_q": float(predicted_qs.detach().mean().item()),
            "target_q": float(target_q.detach().mean().item()),
        }

    def update_actor_temperature(self, batch: TorchBatch) -> Dict[str, float]:
        actions, log_prob = self.actor.sample(
            batch["observations"], reparameterize=True
        )
        with _frozen_parameters(self.critic):
            q_values = self.critic(batch["observations"], actions).min(dim=0).values
        actor_loss = (
            self.temperature.detach() * log_prob - q_values
        ).mean()

        # Official temperature update draws actions at next observations.
        with torch.no_grad():
            _, next_log_prob = self.actor.sample(
                batch["next_observations"], reparameterize=False
            )
            entropy = -next_log_prob.mean()
        temperature_loss = self.temperature * (
            entropy - self.target_entropy
        )

        self.actor_optimizer.zero_grad(set_to_none=True)
        self.temperature_optimizer.zero_grad(set_to_none=True)
        actor_loss.backward()
        temperature_loss.backward()
        self.actor_optimizer.step()
        self.temperature_optimizer.step()

        return {
            "actor_loss": float(actor_loss.detach().item()),
            "temperature_loss": float(temperature_loss.detach().item()),
            "temperature": float(self.temperature.detach().item()),
            "entropy": float(entropy.detach().item()),
        }

    def update_high_utd(self, super_batch: TorchBatch) -> Dict[str, float]:
        """Official WSRL/RLPD high-UTD schedule.

        The super-batch has ``minibatch_size * utd_ratio`` samples. Critic and
        target critic are updated sequentially on every mini-batch. Actor and
        temperature are then updated once on the complete super-batch.
        """
        total_size = next(iter(super_batch.values())).shape[0]
        if total_size % self.config.utd_ratio != 0:
            raise ValueError("Super-batch size must be divisible by utd_ratio.")
        mini_size = total_size // self.config.utd_ratio
        if mini_size != self.config.minibatch_size:
            raise ValueError(
                f"Expected mini-batch size {self.config.minibatch_size}, got {mini_size}."
            )

        critic_metrics: Dict[str, List[float]] = {}
        for update_index in range(self.config.utd_ratio):
            start = update_index * mini_size
            end = start + mini_size
            mini_batch = {key: value[start:end] for key, value in super_batch.items()}
            info = self.update_critic(mini_batch)
            for key, value in info.items():
                critic_metrics.setdefault(key, []).append(value)

        metrics = {
            key: float(np.mean(values)) for key, values in critic_metrics.items()
        }
        metrics.update(self.update_actor_temperature(super_batch))
        return metrics

    def _cql_penalty(
        self,
        batch: TorchBatch,
        q_data: torch.Tensor,
        use_calql: bool,
    ) -> Tuple[torch.Tensor, Dict[str, torch.Tensor]]:
        batch_size = batch["observations"].shape[0]
        n_actions = self.config.cql_n_actions

        random_actions = torch.empty(
            batch_size, n_actions, self.action_dim, device=self.device
        ).uniform_(-1.0, 1.0)
        random_log_density = self.action_dim * math.log(0.5)

        with torch.no_grad():
            current_actions, current_log_probs = self.actor.sample(
                batch["observations"], repeat=n_actions, reparameterize=False
            )
            next_actions, next_log_probs = self.actor.sample(
                batch["next_observations"], repeat=n_actions, reparameterize=False
            )

        q_random = self.critic(batch["observations"], random_actions)
        q_current = self.critic(batch["observations"], current_actions)
        # Released CQL evaluates actions proposed at s' using the current state s.
        q_next = self.critic(batch["observations"], next_actions)

        # The released REDQ+CQL implementation applies the conservative
        # regularizer to a randomly sampled critic subset, while the Bellman
        # loss still trains the full ensemble. Sampling uses randint and may
        # therefore contain duplicate critic indices.
        if self.config.pretrain_num_min_qs < self.critic.ensemble_size:
            cql_indices = torch.randint(
                0,
                self.critic.ensemble_size,
                (self.config.pretrain_num_min_qs,),
                device=self.device,
            )
            q_random = q_random.index_select(0, cql_indices)
            q_current = q_current.index_select(0, cql_indices)
            q_next = q_next.index_select(0, cql_indices)
            q_data_cql = q_data.index_select(0, cql_indices)
        else:
            q_data_cql = q_data

        if use_calql:
            if "mc_returns" not in batch:
                raise KeyError("Cal-QL pre-training requires mc_returns.")
            lower_bound = batch["mc_returns"].view(1, batch_size, 1)
            q_current = torch.maximum(q_current, lower_bound)
            q_next = torch.maximum(q_next, lower_bound)

        if bool(self.config.cql_importance_sample):
            candidates = torch.cat(
                [
                    q_random - random_log_density,
                    q_current - current_log_probs.unsqueeze(0),
                    q_next - next_log_probs.unsqueeze(0),
                ],
                dim=-1,
            )
        else:
            candidates = torch.cat(
                [q_random, q_current, q_next, q_data_cql.unsqueeze(-1)], dim=-1
            )
            # Official non-importance-sampled CQL normalizes the finite action
            # set inside log-sum-exp.
            candidates = candidates - (
                math.log(candidates.shape[-1])
                * float(self.config.cql_temperature)
            )

        temperature = float(self.config.cql_temperature)
        q_ood = temperature * torch.logsumexp(candidates / temperature, dim=-1)
        q_diff = (q_ood - q_data_cql).clamp(
            self.config.cql_clip_diff_min,
            self.config.cql_clip_diff_max,
        )

        if bool(self.config.cql_autotune_alpha):
            alpha_prime = self.cql_alpha_prime
            if alpha_prime is None:
                raise RuntimeError("CQL alpha-prime was not initialized.")
            gap = float(self.config.cql_target_action_gap)
            cql_penalty = alpha_prime.detach() * (q_diff.mean() - gap)
            alpha_prime_loss = -alpha_prime * (
                q_diff.detach().mean() - gap
            )
        else:
            cql_penalty = float(self.config.cql_alpha) * q_diff.mean()
            alpha_prime_loss = torch.zeros((), device=self.device)

        return cql_penalty, {
            "cql_diff": q_diff.mean(),
            "cql_ood_q": q_ood.mean(),
            "cql_alpha_prime_loss": alpha_prime_loss,
        }

    def update_offline(self, batch: TorchBatch, use_calql: bool) -> Dict[str, float]:
        """CQL/Cal-QL initialization update while preserving optimizer states."""
        actions, log_prob = self.actor.sample(
            batch["observations"], reparameterize=True
        )
        with _frozen_parameters(self.critic):
            actor_q = self.critic(batch["observations"], actions).min(dim=0).values
        actor_loss = (
            self.temperature.detach() * log_prob - actor_q
        ).mean()

        with torch.no_grad():
            _, next_log_prob = self.actor.sample(
                batch["next_observations"], reparameterize=False
            )
            entropy = -next_log_prob.mean()
        temperature_loss = self.temperature * (
            entropy - self.target_entropy
        )

        target_q = self._target_q(
            batch,
            max_target_backup=self.config.cql_max_target_backup,
            n_backup_actions=self.config.cql_n_actions,
        )
        q_data = self.critic(batch["observations"], batch["actions"])
        bellman_loss = (q_data - target_q.unsqueeze(0)).pow(2).mean()
        cql_penalty, cql_info = self._cql_penalty(batch, q_data, use_calql)
        critic_loss = bellman_loss + cql_penalty

        self.actor_optimizer.zero_grad(set_to_none=True)
        self.temperature_optimizer.zero_grad(set_to_none=True)
        self.critic_optimizer.zero_grad(set_to_none=True)
        if self.cql_alpha_prime_optimizer is not None:
            self.cql_alpha_prime_optimizer.zero_grad(set_to_none=True)

        actor_loss.backward()
        temperature_loss.backward()
        critic_loss.backward()
        if self.cql_alpha_prime_optimizer is not None:
            cql_info["cql_alpha_prime_loss"].backward()

        self.actor_optimizer.step()
        self.temperature_optimizer.step()
        self.critic_optimizer.step()
        if self.cql_alpha_prime_optimizer is not None:
            self.cql_alpha_prime_optimizer.step()
        _soft_update(self.target_critic, self.critic, self.config.tau)

        metrics = {
            "actor_loss": float(actor_loss.detach().item()),
            "temperature_loss": float(temperature_loss.detach().item()),
            "temperature": float(self.temperature.detach().item()),
            "entropy": float(entropy.detach().item()),
            "critic_loss": float(critic_loss.detach().item()),
            "bellman_loss": float(bellman_loss.detach().item()),
            "cql_penalty": float(cql_penalty.detach().item()),
            "predicted_q": float(q_data.detach().mean().item()),
            "target_q": float(target_q.detach().mean().item()),
            "cql_diff": float(cql_info["cql_diff"].detach().item()),
            "cql_ood_q": float(cql_info["cql_ood_q"].detach().item()),
        }
        if self.cql_alpha_prime is not None:
            metrics["cql_alpha_prime"] = float(
                self.cql_alpha_prime.detach().item()
            )
            metrics["cql_alpha_prime_loss"] = float(
                cql_info["cql_alpha_prime_loss"].detach().item()
            )
        return metrics

    def checkpoint(self, config: TrainConfig, phase: str, step: int) -> Dict:
        payload = {
            "actor": self.actor.state_dict(),
            "critic": self.critic.state_dict(),
            "target_critic": self.target_critic.state_dict(),
            "raw_temperature": self.raw_temperature.detach().cpu(),
            "actor_optimizer": self.actor_optimizer.state_dict(),
            "critic_optimizer": self.critic_optimizer.state_dict(),
            "temperature_optimizer": self.temperature_optimizer.state_dict(),
            "phase": phase,
            "step": int(step),
            "config": asdict(config),
        }
        if self.raw_cql_alpha_prime is not None:
            payload["raw_cql_alpha_prime"] = self.raw_cql_alpha_prime.detach().cpu()
        if self.cql_alpha_prime_optimizer is not None:
            payload["cql_alpha_prime_optimizer"] = (
                self.cql_alpha_prime_optimizer.state_dict()
            )
        return payload

    def load_checkpoint(
        self,
        path: str,
        strict: bool,
        restore_optimizer_states: bool,
    ) -> Dict:
        checkpoint = torch.load(path, map_location=self.device)
        self.actor.load_state_dict(checkpoint["actor"], strict=strict)
        self.critic.load_state_dict(checkpoint["critic"], strict=strict)
        if "target_critic" in checkpoint:
            self.target_critic.load_state_dict(
                checkpoint["target_critic"], strict=strict
            )
        else:
            self.target_critic.load_state_dict(self.critic.state_dict())

        if "raw_temperature" in checkpoint:
            with torch.no_grad():
                self.raw_temperature.copy_(
                    torch.as_tensor(
                        checkpoint["raw_temperature"], device=self.device
                    )
                )

        if restore_optimizer_states:
            required = (
                "actor_optimizer",
                "critic_optimizer",
                "temperature_optimizer",
            )
            missing = [key for key in required if key not in checkpoint]
            if missing and strict:
                raise KeyError(
                    "Checkpoint lacks optimizer states required by WSRL: "
                    + ", ".join(missing)
                )
            if "actor_optimizer" in checkpoint:
                self.actor_optimizer.load_state_dict(checkpoint["actor_optimizer"])
            if "critic_optimizer" in checkpoint:
                self.critic_optimizer.load_state_dict(checkpoint["critic_optimizer"])
            if "temperature_optimizer" in checkpoint:
                self.temperature_optimizer.load_state_dict(
                    checkpoint["temperature_optimizer"]
                )
        return checkpoint


# -----------------------------------------------------------------------------
# Batch conversion, evaluation, and checkpoint helpers
# -----------------------------------------------------------------------------


def _to_torch_batch(batch: NumpyBatch, device: torch.device) -> TorchBatch:
    output: TorchBatch = {
        "observations": torch.as_tensor(
            batch["observations"], dtype=torch.float32, device=device
        ),
        "actions": torch.as_tensor(
            batch["actions"], dtype=torch.float32, device=device
        ),
        "rewards": torch.as_tensor(
            batch["rewards"], dtype=torch.float32, device=device
        ).reshape(-1),
        "masks": torch.as_tensor(
            batch["masks"], dtype=torch.float32, device=device
        ).reshape(-1),
        "dones": torch.as_tensor(
            batch["dones"], dtype=torch.bool, device=device
        ).reshape(-1),
        "next_observations": torch.as_tensor(
            batch["next_observations"], dtype=torch.float32, device=device
        ),
    }
    if "mc_returns" in batch:
        output["mc_returns"] = torch.as_tensor(
            batch["mc_returns"], dtype=torch.float32, device=device
        ).reshape(-1)
    return output


@torch.no_grad()
def evaluate(
    actor: TanhGaussianActor,
    env: gym.Env,
    device: torch.device,
    episodes: int,
    env_name: str,
) -> Dict[str, float]:
    """Evaluate WSRL with protocol-appropriate metrics.

    Standard D4RL Adroit uses D4RL normalized return for direct comparison
    with the unified RLPD/RiBES benchmark; Adroit-Binary keeps WSRL success.
    """
    env_type = _env_type(env_name)
    returns: List[float] = []
    lengths: List[int] = []
    adroit_binary_successes: List[float] = []
    kitchen_stages: List[float] = []
    normalized_scores: List[float] = []

    actor.eval()
    for _ in range(episodes):
        observation = _reset_env(env)
        terminated = False
        truncated = False
        episode_return = 0.0
        episode_length = 0
        goal_achieved = False
        final_reward = 0.0

        while not (terminated or truncated):
            action = actor.eval_action(observation, device)
            observation, reward, terminated, truncated, info = _step_env(env, action)
            episode_return += reward
            episode_length += 1
            final_reward = float(reward)
            if env_type == "adroit_binary":
                goal_achieved = goal_achieved or bool(info.get("goal_achieved", False))

        returns.append(episode_return)
        lengths.append(episode_length)

        if env_type == "adroit_binary":
            adroit_binary_successes.append(float(goal_achieved))
        elif env_type == "kitchen":
            # Released WSRL evaluation treats the final raw Kitchen reward as
            # the number of solved stages and divides by four for success rate.
            kitchen_stages.append(final_reward)
        elif env_type in {"antmaze", "locomotion", "adroit_d4rl"}:
            normalized = _get_normalized_score(env, episode_return)
            if normalized is not None:
                normalized_scores.append(normalized)

    actor.train()
    result: Dict[str, float] = {
        "return": float(np.mean(returns)),
        "length": float(np.mean(lengths)),
    }
    if adroit_binary_successes:
        result["success_rate"] = float(np.mean(adroit_binary_successes))
    if kitchen_stages:
        stages = float(np.mean(kitchen_stages))
        result["num_stages_solved"] = stages
        result["success_rate"] = stages / 4.0
    if normalized_scores:
        result["d4rl_normalized_score"] = float(np.mean(normalized_scores))
        # For AntMaze, normalized score / 100 is also the success-rate scale
        # used by the released implementation. We do not relabel locomotion as
        # success in TensorBoard, but retain the normalized score for both.
        if env_type == "antmaze":
            result["success_rate"] = result["d4rl_normalized_score"] / 100.0
    return result


def _get_normalized_score(env: gym.Env, raw_return: float) -> Optional[float]:
    candidate = env
    for _ in range(16):
        if hasattr(candidate, "get_normalized_score"):
            try:
                return float(candidate.get_normalized_score(raw_return) * 100.0)
            except Exception:
                return None
        if not hasattr(candidate, "env"):
            break
        candidate = candidate.env
    return None


def _save_checkpoint(
    learner: WSRLLearner,
    config: TrainConfig,
    run_name: str,
    phase: str,
    step: int,
) -> Optional[str]:
    if config.checkpoints_path is None:
        return None
    directory = Path(config.checkpoints_path) / run_name
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / f"{phase}_{step}.pt"
    torch.save(learner.checkpoint(config, phase, step), path)
    return str(path)


def _set_seed(seed: int, deterministic_torch: bool) -> None:
    os.environ["PYTHONHASHSEED"] = str(seed)
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
    if deterministic_torch:
        torch.use_deterministic_algorithms(True)
        torch.backends.cudnn.deterministic = True
        torch.backends.cudnn.benchmark = False


# -----------------------------------------------------------------------------
# Training
# -----------------------------------------------------------------------------


def train(config: TrainConfig) -> None:
    _resolve_official_preset(config)
    _validate_config(config)
    _set_seed(config.train_seed, config.deterministic_torch)
    device = torch.device(config.device)

    train_env = wrap_env(gym.make(config.env_name), config, training=True)
    eval_env = wrap_env(gym.make(config.env_name), config, training=False)
    _seed_env(train_env, config.train_seed)
    _seed_env(eval_env, config.train_seed + config.eval_seed_offset)

    if not isinstance(train_env.observation_space, gym.spaces.Box):
        raise TypeError("Wrapped observation space must be Box.")
    if not isinstance(train_env.action_space, gym.spaces.Box):
        raise TypeError("Wrapped action space must be Box.")
    observation_dim = int(np.prod(train_env.observation_space.shape))
    action_dim = int(np.prod(train_env.action_space.shape))

    actor = TanhGaussianActor(
        observation_dim,
        action_dim,
        config.actor_hidden_dims,
        config.std_parameterization,
        config,
    ).to(device)
    critic = CriticEnsemble(
        observation_dim,
        action_dim,
        config.critic_hidden_dims,
        config.num_critics,
        config,
    ).to(device)
    learner = WSRLLearner(actor, critic, action_dim, config, device)

    run_name = (
        f"{config.env_name}_seed{config.train_seed}_"
        f"Q{config.num_critics}_UTD{config.utd_ratio}"
    )
    log_dir = Path(config.log_root) / config.env_name.split("-")[0] / run_name
    log_dir.mkdir(parents=True, exist_ok=True)
    writer = SummaryWriter(log_dir=str(log_dir))

    print(
        f"env={config.env_name}\n"
        f"preset={_preset_label(config.env_name)}\n"
        f"device={device}\n"
        f"initialization={config.initialization_mode}/{config.offline_algorithm}\n"
        f"dataset_source={config.dataset_source}, reward_transform="
        f"{config.reward_scale}*r+{config.reward_bias}\n"
        f"actor_hidden={config.actor_hidden_dims}\n"
        f"critic_hidden={config.critic_hidden_dims}\n"
        f"critics={config.num_critics}, online_num_min_qs={config.online_num_min_qs}\n"
        f"online_max_target_backup={config.max_target_backup}, "
        f"offline_cql_max_target_backup={config.cql_max_target_backup}\n"
        f"warmup_steps={config.warmup_steps}\n"
        f"online updates/env-step: critic={config.utd_ratio}, actor=1, temperature=1\n"
        f"critic mini-batch={config.minibatch_size}, actor super-batch="
        f"{config.minibatch_size * config.utd_ratio}\n"
        f"offline data retained online=0\n"
        f"log_dir={log_dir}",
        flush=True,
    )

    # ------------------------------------------------------------------
    # Phase 1: offline initialization
    # ------------------------------------------------------------------
    if config.initialization_mode == "load":
        checkpoint = learner.load_checkpoint(
            config.pretrained_checkpoint,
            strict=config.strict_checkpoint,
            restore_optimizer_states=config.restore_optimizer_states,
        )
        print(
            f"Loaded pre-trained checkpoint: {config.pretrained_checkpoint} "
            f"(phase={checkpoint.get('phase', 'unknown')}, "
            f"step={checkpoint.get('step', 'unknown')})",
            flush=True,
        )
    else:
        if config.dataset_source == "adroit_binary":
            arrays = _load_adroit_binary_dataset(config)
        else:
            arrays = _load_d4rl_dataset(train_env, config)
        offline_dataset = ArrayDataset(arrays, seed=config.dataset_seed)
        use_calql = config.offline_algorithm == "calql"

        for step in trange(int(config.pretrain_steps), desc="Offline initialization"):
            batch = _to_torch_batch(
                offline_dataset.sample(config.minibatch_size), device
            )
            metrics = learner.update_offline(batch, use_calql=use_calql)

            if step % config.log_every == 0:
                for key, value in metrics.items():
                    writer.add_scalar(f"offline-training/{key}", value, step)
            if step % config.eval_every == 0:
                evaluation = evaluate(
                    learner.actor,
                    eval_env,
                    device,
                    config.eval_episodes,
                    config.env_name,
                )
                for key, value in evaluation.items():
                    writer.add_scalar(f"offline-evaluation/{key}", value, step)
                writer.flush()

        _save_checkpoint(
            learner,
            config,
            run_name,
            "offline_pretrained",
            int(config.pretrain_steps),
        )

        # The main WSRL setting explicitly does not retain offline transitions.
        del offline_dataset
        del arrays

    learner.switch_to_online_wsrl()

    offline_evaluation = evaluate(
        learner.actor,
        eval_env,
        device,
        config.eval_episodes,
        config.env_name,
    )
    pretrained_message = (
        f"[pretrained evaluation] return={offline_evaluation['return']:.3f}, "
        f"length={offline_evaluation['length']:.1f}"
    )
    for key in ("d4rl_normalized_score", "success_rate", "num_stages_solved"):
        if key in offline_evaluation:
            pretrained_message += f", {key}={offline_evaluation[key]:.3f}"
    print(pretrained_message, flush=True)

    # Frozen policy used only during the warm-up interaction phase.
    frozen_pretrained_actor = deepcopy(learner.actor).to(device)
    frozen_pretrained_actor.eval()
    frozen_pretrained_actor.requires_grad_(False)

    replay_buffer = ReplayBuffer(
        train_env.observation_space,
        train_env.action_space,
        config.replay_buffer_capacity,
        seed=config.train_seed,
    )

    # ------------------------------------------------------------------
    # Phases 2 and 3: warm-up, then online-only high-UTD SAC
    # ------------------------------------------------------------------
    observation = _reset_env(train_env)
    episode_return = 0.0
    episode_length = 0
    super_batch_size = config.minibatch_size * config.utd_ratio

    for online_step in trange(config.online_steps, desc="WSRL online fine-tuning"):
        if online_step < config.warmup_steps:
            action = frozen_pretrained_actor.sample_action(observation, device)
        else:
            action = learner.actor.sample_action(observation, device)
        if _env_type(config.env_name) in {"antmaze", "kitchen", "locomotion", "adroit_d4rl"}:
            action = np.clip(action, -config.clip_action, config.clip_action)

        (
            next_observation,
            reward,
            terminated,
            truncated,
            info,
        ) = _step_env(train_env, action)
        done = bool(terminated or truncated)
        mask = 0.0 if terminated else 1.0
        replay_buffer.insert(
            observation,
            action,
            reward,
            mask,
            done,
            next_observation,
        )

        episode_return += reward
        episode_length += 1
        observation = next_observation
        if done:
            writer.add_scalar("online-training/episode_return", episode_return, online_step)
            writer.add_scalar("online-training/episode_length", episode_length, online_step)
            observation = _reset_env(train_env)
            episode_return = 0.0
            episode_length = 0

        metrics: Dict[str, float] = {}
        if online_step >= config.warmup_steps:
            super_batch = _to_torch_batch(
                replay_buffer.sample(super_batch_size), device
            )
            metrics = learner.update_high_utd(super_batch)

        if metrics and online_step % config.log_every == 0:
            for key, value in metrics.items():
                writer.add_scalar(f"online-training/{key}", value, online_step)
            writer.add_scalar(
                "online-training/replay_size", replay_buffer.size, online_step
            )
            writer.flush()

        if (
            online_step % config.eval_every == 0
            or online_step == config.warmup_steps
            or online_step == config.online_steps - 1
        ):
            evaluation = evaluate(
                learner.actor,
                eval_env,
                device,
                config.eval_episodes,
                config.env_name,
            )
            for key, value in evaluation.items():
                writer.add_scalar(f"online-evaluation/{key}", value, online_step)
            message = (
                f"[online eval] step={online_step}, "
                f"return={evaluation['return']:.3f}, "
                f"length={evaluation['length']:.1f}"
            )
            for key in ("d4rl_normalized_score", "success_rate", "num_stages_solved"):
                if key in evaluation:
                    message += f", {key}={evaluation[key]:.3f}"
            print(message, flush=True)
            writer.flush()

        if (
            config.checkpoints_path is not None
            and online_step > 0
            and online_step % config.save_every == 0
        ):
            _save_checkpoint(
                learner, config, run_name, "online", online_step
            )

    _save_checkpoint(
        learner, config, run_name, "final", config.online_steps
    )
    writer.close()
    train_env.close()
    eval_env.close()


if __name__ == "__main__":
    train(pyrallis.parse(config_class=TrainConfig))
